### ISSUE TITLE
Custom fields is not compatible anymore to new rubygems

### ISSUE THREAD

**Issue by danielschlegel** [locomotivecms/custom_fields#37]
I cannot bundle install locomotivecms anymore with new rubygems version 3.0.1

```
Bundler could not find compatible versions for gem "rubygems":
  In Gemfile:
    rubygems (= 3.0.1)

    locomotivecms was resolved to 3.4.1, which depends on
      custom_fields (~> 2.9.0) was resolved to 2.9.0, which depends on
        rubygems (~> 2.4)
```

**Comment by nflorentin** [comment]
+1

**Comment by kapralVV** [comment]
Hi @danielschlegel  and @nflorentin 
I've faced the same issue. 
Could you tell me what does it mean. And is it possible to fix it somehow. 
I mean do you know how to solve it quickly. Please help.

**Comment by danielschlegel** [comment]
I do not have any fix atm.

**Comment by getninjaN** [comment]
If you're using rvm you could run `rvm install rubygems 2.4.8 --force` to install an older version.
After that I was able to install custom_fields.
